# Generated by Django 3.0 on 2020-06-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_rating', models.IntegerField(max_length=10)),
                ('design_rating', models.IntegerField(max_length=10)),
                ('usability_rating', models.IntegerField(max_length=10)),
                ('overall_rating', models.IntegerField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratingapp.Project')),
            ],
        ),
    ]
