# Generated by Django 3.0 on 2020-06-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='overall_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability_rating',
            field=models.IntegerField(),
        ),
    ]
