# Generated by Django 3.0 on 2020-06-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0005_auto_20200607_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
