# Generated by Django 3.0 on 2020-06-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0009_auto_20200608_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ratings',
        ),
    ]
