# Generated by Django 3.0 on 2020-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0010_remove_project_ratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='project',
            name='average_content_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_design_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_usability_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='content_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='design_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(),
        ),
    ]
